version: '2.1'
services:
  scrabble-api:
    image: tomcat:8.5.8
    hostname: scrabble-api
    container_name: scrabble-api
    depends_on:
     scrabble-cassandra:
       condition: service_healthy
     scrabble-mysql:
       condition: service_started
     scrabble-redis:
       condition: service_started
    volumes:
     - ./target/scrabble-api.war:/usr/local/tomcat/webapps/scrabble-api.war
     - ./src/main/resources/dictionary:/tmp/scrabble-data/dictionary
    ports:
     - "8080:8080"
    networks:
     - backend
  scrabble-cassandra:
    image: cassandra:3.4
    hostname: scrabble-cassandra
    container_name: scrabble-cassandra
    volumes:
     - ./src/main/resources/gamedata.cql:/var/lib/cassandra/gamedata.cql
    healthcheck:
      test: "exit 0"
    ports:
     - 9042
    networks:
     - backend
  scrabble-redis:
    image: redis:4.0
    hostname: scrabble-redis
    container_name: scrabble-redis
    ports:
     - 6379
    networks:
     - backend
  scrabble-mysql:
    image: mysql:5.6
    container_name: scrabble-mysql
    environment:
      MYSQL_ROOT_PASSWORD: diabloii
      MYSQL_USER: scrabble_user
      MYSQL_PASSWORD: scrabble_pass
      MYSQL_DATABASE: scrabble
    volumes:
     - ./src/main/resources/gamedata.sql:/var/lib/mysql/gamedata.sql
    networks:
     - backend
networks:
    backend:
      name: scrabble-backend
      driver: bridge