-- pre-defined users
insert into users (username, name, surname, email, password, enabled) values ('Edi', 'Edi', 'Susam', 'tester@gmail.com', '$2a$10$kL2cVFyQ9FIRm390RG8JienR/nJVTK8g6Lb0FH0K5Y4AEsE1zZLVm', 1);
insert into users (username, name, surname, email, password, enabled) values ('Budu', 'Büdü', 'Susam', 'player@gmail.com', '$2a$10$kL2cVFyQ9FIRm390RG8JienR/nJVTK8g6Lb0FH0K5Y4AEsE1zZLVm', 1);
insert into users (username, name, surname, email, password, enabled) values ('admin', 'Admin', 'User', 'admin@gmail.com', '$2a$10$kL2cVFyQ9FIRm390RG8JienR/nJVTK8g6Lb0FH0K5Y4AEsE1zZLVm', 1);
insert into users (username, name, surname, email, password, enabled) values ('redis_user', 'Redis', 'User', 'redis@gmail.com', '$2a$10$kL2cVFyQ9FIRm390RG8JienR/nJVTK8g6Lb0FH0K5Y4AEsE1zZLVm', 1);
-- application roles
insert into roles (rolename, enabled) values ('ROLE_USER', 1);
insert into roles (rolename, enabled) values ('ROLE_ADMIN', 1);
insert into roles (rolename, enabled) values ('ROLE_SYSTEM', 1);
-- user defined roles
insert into user_roles (username, rolename, enabled) values ('Edi', 'ROLE_USER', 1);
insert into user_roles (username, rolename, enabled) values ('admin', 'ROLE_ADMIN', 1);
insert into user_roles (username, rolename, enabled) values ('Budu', 'ROLE_USER', 1);
insert into user_roles (username, rolename, enabled) values ('redis_user', 'ROLE_SYSTEM', 1);
-- game rule sets
insert into rules (column_size, row_size, cell_size, rack_size, language) values (15, 15, 255, 7, 'tr');
-- letter rules
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'A', 12, 1, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'B', 2, 3);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'C', 2, 4);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'Ç', 2, 4);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'D', 2, 3);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'E', 8, 1, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'F', 1, 7);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'G', 1, 5);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'Ğ', 1, 8);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'H', 1, 5);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'I', 4, 2, 1);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'İ', 7, 1, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'J', 1, 10);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'K', 7, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'L', 7, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'M', 4, 2);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'N', 5, 1);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'O', 3, 2, 1);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'Ö', 1, 7, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'P', 1, 5);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'R', 6, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'S', 3, 2);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'Ş', 2, 4);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'T', 5, 1);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'U', 3, 2, 1);
insert into tile_rules (rule_id, letter, piece, score, vowel) values (1, 'Ü', 2, 3, 1);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'V', 1, 7);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'Y', 2, 3);
insert into tile_rules (rule_id, letter, piece, score) values (1, 'Z', 2, 4);
-- cell define rules
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (1, 1, 1, 1, 'red', 1, 3, 1, 0, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (2, 1, 2, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (3, 1, 3, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (4, 1, 4, 1, 'grey', 2, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (5, 1, 5, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (6, 1, 6, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (7, 1, 7, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (8, 1, 8, 1, 'red', 1, 3, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (9, 1, 9, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (10, 1, 10, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (11, 1, 11, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (12, 1, 12, 1, 'grey', 2, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (13, 1, 13, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (14, 1, 14, 1, 'white', 1, 1, 1, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (15, 1, 15, 1, 'red', 1, 3, 0, 1, 0, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (16, 2, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (17, 2, 2, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (18, 2, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (19, 2, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (20, 2, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (21, 2, 6, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (22, 2, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (23, 2, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (24, 2, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (25, 2, 10, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (26, 2, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (27, 2, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (28, 2, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (29, 2, 14, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (30, 2, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (31, 3, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (32, 3, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (33, 3, 3, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (34, 3, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (35, 3, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (36, 3, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (37, 3, 7, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (38, 3, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (39, 3, 9, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (40, 3, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (41, 3, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (42, 3, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (43, 3, 13, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (44, 3, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (45, 3, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (46, 4, 1, 1, 'grey', 2, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (47, 4, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (48, 4, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (49, 4, 4, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (50, 4, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (51, 4, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (52, 4, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (53, 4, 8, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (54, 4, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (55, 4, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (56, 4, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (57, 4, 12, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (58, 4, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (59, 4, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (60, 4, 15, 1, 'grey', 2, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (61, 5, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (62, 5, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (63, 5, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (64, 5, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (65, 5, 5, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (66, 5, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (67, 5, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (68, 5, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (69, 5, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (70, 5, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (71, 5, 11, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (72, 5, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (73, 5, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (74, 5, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (75, 5, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (76, 6, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (77, 6, 2, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (78, 6, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (79, 6, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (80, 6, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (81, 6, 6, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (82, 6, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (83, 6, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (84, 6, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (85, 6, 10, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (86, 6, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (87, 6, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (88, 6, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (89, 6, 14, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (90, 6, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (91, 7, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (92, 7, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (93, 7, 3, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (94, 7, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (95, 7, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (96, 7, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (97, 7, 7, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (98, 7, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (99, 7, 9, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (100, 7, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (101, 7, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (102, 7, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (103, 7, 13, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (104, 7, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (105, 7, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (106, 8, 1, 1, 'red', 1, 3, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (107, 8, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (108, 8, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (109, 8, 4, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (110, 8, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (111, 8, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (112, 8, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom, starting_cell) values (113, 8, 8, 1, 'star', 1, 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (114, 8, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (115, 8, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (116, 8, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (117, 8, 12, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (118, 8, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (119, 8, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (120, 8, 15, 1, 'red', 1, 3, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (121, 9, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (122, 9, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (123, 9, 3, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (124, 9, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (125, 9, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (126, 9, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (127, 9, 7, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (128, 9, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (129, 9, 9, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (130, 9, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (131, 9, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (132, 9, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (133, 9, 13, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (134, 9, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (135, 9, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (136, 10, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (137, 10, 2, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (138, 10, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (139, 10, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (140, 10, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (141, 10, 6, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (142, 10, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (143, 10, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (144, 10, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (145, 10, 10, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (146, 10, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (147, 10, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (148, 10, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (149, 10, 14, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (150, 10, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (151, 11, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (152, 11, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (153, 11, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (154, 11, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (155, 11, 5, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (156, 11, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (157, 11, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (158, 11, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (159, 11, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (160, 11, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (161, 11, 11, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (162, 11, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (163, 11, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (164, 11, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (165, 11, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (166, 12, 1, 1, 'grey', 2, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (167, 12, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (168, 12, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (169, 12, 4, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (170, 12, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (171, 12, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (172, 12, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (173, 12, 8, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (174, 12, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (175, 12, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (176, 12, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (177, 12, 12, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (178, 12, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (179, 12, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (180, 12, 15, 1, 'grey', 2, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (181, 13, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (182, 13, 2, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (183, 13, 3, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (184, 13, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (185, 13, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (186, 13, 6, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (187, 13, 7, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (188, 13, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (189, 13, 9, 1, 'grey', 2, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (190, 13, 10, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (191, 13, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (192, 13, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (193, 13, 13, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (194, 13, 14, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (195, 13, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (196, 14, 1, 1, 'white', 1, 1, 1, 0, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (197, 14, 2, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (198, 14, 3, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (199, 14, 4, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (200, 14, 5, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (201, 14, 6, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (202, 14, 7, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (203, 14, 8, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (204, 14, 9, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (205, 14, 10, 1, 'green', 3, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (206, 14, 11, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (207, 14, 12, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (208, 14, 13, 1, 'white', 1, 1, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (209, 14, 14, 1, 'orange', 1, 2, 1, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (210, 14, 15, 1, 'white', 1, 1, 0, 1, 1, 1);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (211, 15, 1, 1, 'red', 1, 3, 1, 0, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (212, 15, 2, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (213, 15, 3, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (214, 15, 4, 1, 'grey', 2, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (215, 15, 5, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (216, 15, 6, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (217, 15, 7, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (218, 15, 8, 1, 'red', 1, 3, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (219, 15, 9, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (220, 15, 10, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (221, 15, 11, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (222, 15, 12, 1, 'grey', 2, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (223, 15, 13, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (224, 15, 14, 1, 'white', 1, 1, 1, 1, 1, 0);
insert into cell_rules (cell_number, row_number, column_number, rule_id, color, letter_multiplier, word_multiplier, has_right, has_left, has_top, has_bottom) values (225, 15, 15, 1, 'red', 1, 3, 0, 1, 1, 0);